import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { books } from './data/books'
import { projects } from './data/projects'
import { publications } from './data/publications'
import { timeline } from './data/timeline'
import './styles.css'

const nav = [['about', 'О научном пути'], ['works', 'Труды'], ['projects', 'Проекты'], ['activity', 'Деятельность'], ['sources', 'Источники']]
const themes = ['культура безопасности', 'дошкольное образование', 'начальное образование', 'исследовательская деятельность', 'функциональная грамотность', 'естественно-научная грамотность', 'социальная грамотность', 'информационная культура', 'профессиональное развитие педагогов']

function App() {
  const [menu, setMenu] = useState(false)
  const [query, setQuery] = useState('')
  const [year, setYear] = useState('Все годы')
  const [type, setType] = useState('Все типы')
  const [top, setTop] = useState(false)
  useEffect(() => { const onScroll = () => setTop(window.scrollY > 600); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll) }, [])
  const filtered = useMemo(() => publications.filter(p => (year === 'Все годы' || p.year === Number(year)) && (type === 'Все типы' || p.type === type) && `${p.title} ${p.venue} ${p.authors ?? ''}`.toLowerCase().includes(query.toLowerCase())), [query, year, type])
  const years = [...new Set(publications.map(p => p.year))].sort((a,b) => b-a)
  const scroll = (id: string) => { setMenu(false); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }) }
  return <>
    <header className="header"><a className="brand" href="#top" aria-label="На главную"><span>ЛЛТ</span><i>Академический архив</i></a><button className="menu" onClick={() => setMenu(!menu)} aria-expanded={menu}>Меню</button><nav className={menu ? 'open' : ''}>{nav.map(([id, label]) => <button key={id} onClick={() => scroll(id)}>{label}</button>)}</nav></header>
    <main id="top">
      <section className="hero"><div className="hero-copy"><p className="eyebrow">Научный архив · Орёл — Москва</p><h1>Лилия Львовна<br/><em>Тимофеева</em></h1><p className="degree">Доктор педагогических наук</p><p className="intro">Исследователь, автор образовательных программ и учебно-методических материалов в области дошкольного и начального образования.</p><div className="actions"><button onClick={() => scroll('about')} className="primary">Научный путь <b>↓</b></button><button onClick={() => scroll('works')} className="secondary">Публикации</button></div></div><div className="hero-art" aria-hidden="true"><div className="sun"></div><div className="book book-a"></div><div className="book book-b"></div><div className="note">1990<br/><strong>→</strong><br/>2026</div><div className="line"></div></div></section>
      <section className="statement" id="about"><p className="section-kicker">01 / Биография</p><div><h2>Научная жизнь —<br/>как путь и наследие.</h2><p className="lead">Исследовательская траектория Лилии Львовны объединяет дидактику, исследовательское обучение, дошкольное и начальное образование, формирование культуры безопасности и современную грамотность.</p><p>Профессиональный путь связан с Орлом и Москвой. В современных официальных материалах она представлена как профессор МПСУ и исследователь Института стратегии развития образования РАО.</p><div className="notice">Сведения на странице собраны из материалов, переданных для первого архивного этапа. Записи с пометкой «уточняется» требуют сверки с первоисточником.</div></div></section>
      <section className="timeline-section"><div className="section-heading"><p className="section-kicker">02 / Хронология</p><h2>Вехи научного пути</h2></div><ol className="timeline">{timeline.map(item => <li key={item.year}><span className="dot"></span><div className="time">{item.year}</div><div><h3>{item.title} {item.status === 'verify' && <small>уточняется</small>}</h3><p>{item.text}</p></div></li>)}</ol></section>
      <section className="degrees"><div className="section-heading"><p className="section-kicker">03 / Научные степени</p><h2>Исследования,<br/>задавшие направление</h2></div><div className="degree-grid"><article><span>2000</span><h3>Кандидат педагогических наук</h3><p>«Дидактические условия формирования у учащихся умений и навыков использования научных методов познания»</p></article><article><span>2022</span><h3>Доктор педагогических наук</h3><p>«Концепция формирования культуры безопасности у детей дошкольного и младшего школьного возраста»</p></article></div></section>
      <section className="themes"><p className="section-kicker">04 / Исследовательское поле</p><div className="theme-list">{themes.map((theme, i) => <span key={theme} style={{'--i': i} as React.CSSProperties}>{theme}</span>)}</div></section>
      <section id="works" className="works"><div className="section-heading"><p className="section-kicker">05 / Издания</p><h2>Книги и<br/>методические материалы</h2></div><div className="book-grid">{books.map((book, i) => <article className={'book-card shade-'+i%4} key={book.title}><div className="spine">{book.category}</div><div><p className="book-meta">{book.year ?? 'Архивное издание'} {book.publisher && ` · ${book.publisher}`}</p><h3>{book.title}</h3>{book.authors && <p>{book.authors}</p>}{book.note && <small>{book.note}</small>}</div></article>)}</div></section>
      <section id="projects" className="projects"><div className="section-heading"><p className="section-kicker">06 / Практика</p><h2>Авторские программы<br/>и проекты</h2></div><div className="project-grid">{projects.map((project, i) => <article key={project.title}><div className="project-num">0{i+1}</div><p className="label">{project.label}</p><h3>{project.title}</h3><p>{project.description}</p>{project.status === 'verify' && <small>требует документальной сверки</small>}</article>)}</div></section>
      <section className="publications"><div className="section-heading"><p className="section-kicker">07 / Библиография</p><h2>Публикации</h2><p className="caption">Архитектура каталога рассчитана на расширение до полного научного списка.</p></div><div className="filters"><label><span className="sr-only">Поиск публикаций</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Поиск по названию…" /></label><select value={year} onChange={e => setYear(e.target.value)}><option>Все годы</option>{years.map(y => <option key={y}>{y}</option>)}</select><select value={type} onChange={e => setType(e.target.value)}><option>Все типы</option>{[...new Set(publications.map(p=>p.type))].map(t => <option key={t}>{t}</option>)}</select></div><div className="pub-list" aria-live="polite">{filtered.length ? filtered.map(p => <article key={p.title}><div><span>{p.year}</span><b>{p.type}</b></div><div><h3>{p.title}</h3><p>{p.venue}{p.authors && ` · ${p.authors}`}</p>{p.id && <small>{p.id}</small>}</div>{p.verified && <i title="Подтверждено в исходных материалах">✓</i>}</article>) : <p className="empty">По этому запросу пока нет записей.</p>}</div></section>
      <section id="activity" className="activity"><p className="section-kicker">08 / Экспертное сообщество</p><h2>Экспертная и редакторская<br/>деятельность</h2><div className="activity-grid"><div><h3>Образование и наука</h3><p>МПСУ · Институт стратегии развития образования РАО · федеральный эксперт Национальной родительской ассоциации</p></div><div><h3>Экспертиза</h3><p>«Воспитатели России» · экспертные советы · «Безопасная информационная среда детства»</p></div><div><h3>Редакционная работа</h3><p>Научный редактор «Высшего образования сегодня»; работа с профессиональными журналами и методическими сериями.</p></div></div></section>
      <section className="lectures"><div><p className="section-kicker">09 / Открытый диалог</p><h2>Лекции и выступления</h2></div><ul><li><span>2022</span>Проектно-исследовательская деятельность в начальной школе</li><li><span>2023</span>Реализуем ФОП ДО: предпосылки функциональной грамотности</li><li><span>2024</span>Функциональная грамотность — характеристика современной личности</li><li><span>2025</span>Серия мероприятий по социальной грамотности и естественно-научному образованию</li></ul></section>
      <section className="identity"><div><p className="section-kicker">10 / Идентификаторы</p><h2>Научный профиль</h2></div><a href="https://orcid.org/0000-0002-7944-9796" target="_blank" rel="noreferrer"><span>ORCID</span><strong>0000-0002-7944-9796</strong><b>↗</b></a></section>
      <section id="sources" className="sources"><p className="section-kicker">11 / Архивная точность</p><h2>Источники и статус верификации</h2><p>Основные направления для документального пополнения архива: Российская государственная библиотека, Институт стратегии развития образования РАО, МПСУ, издательства «Просвещение» и «Детство-Пресс», научные журналы и каталоги.</p><div className="source-grid"><a href="https://search.rsl.ru/" target="_blank" rel="noreferrer">РГБ <b>↗</b></a><a href="https://www.instrao.ru/" target="_blank" rel="noreferrer">РАО / ИСРО <b>↗</b></a><a href="https://www.mpsu.ru/" target="_blank" rel="noreferrer">МПСУ <b>↗</b></a><a href="https://prosv.ru/" target="_blank" rel="noreferrer">Просвещение <b>↗</b></a></div><p className="todo"><strong>TODO для архива:</strong> добавить постоянные ссылки, ISBN, полный список публикаций, подтверждённые EDN/AuthorID и разрешённые к публикации фотографии.</p></section>
    </main>
    <footer><span>Л. Л. Тимофеева</span><span>Академический архив · 2026</span><a href="#top">К началу ↑</a></footer>
    {top && <button className="back" onClick={() => scroll('top')} aria-label="Вернуться к началу">↑</button>}
  </>
}
createRoot(document.getElementById('root')!).render(<App />)
